### PR TITLE
widen signature for draw! and AbstractArray->AbstractMatrix

### LINKED ISSUE #42: is argument signature for draw! too restrictive?
The `draw!` method for abstract arrays requires that both arguments be the same type, but the destination array is created with `copy` which doesn't always give you back an AbstractArray of the same type: 

```julia
julia> typeof(view(1:100, 1:2:100))
SubArray{Int64,1,UnitRange{Int64},Tuple{StepRange{Int64,Int64}},true}

julia> typeof(copy(view(1:100, 1:2:100)))
Array{Int64,1}
```

### PR DESCRIPTION
**Pull request by kleinschmidt**
Two small changes: `draw!` no longer restricts source and destination `AbstractVector`s to be of the same type, and I changed the method with `AbstractArray` arguments to be `AbstractMatrix` because slices are taken with `x[i, :]` which only works for a matrix now.

fixes #42

### CODE REVIEW

**Comment by kleinschmidt** [comment]
like that?

**Comment by kleinschmidt** [comment]
(I can rebase manually if need be...)

**Comment by juliangehring** [comment]
Perfect, thanks for the nice improvement!

**Comment by kleinschmidt** [comment]
My pleasure. Thanks for all your work on this package!

**Pull request merged**
