### PR TITLE
Use SafeTestsets

### PR DESCRIPTION
**Pull request by devmotion**
This PR uses SafeTestsets for running tests in separate modules. Was a part of https://github.com/juliangehring/Bootstrap.jl/pull/50.

### CODE REVIEW

**Comment by juliangehring** [comment]
Thanks, that is a nice idea! However, I'm not sure whether is really brings a good benefit in the end.
Afaics, this brings in an additional dependency (`SafeTestsets`) and we only really save the module definition in each test file. Having the tests explicitly wrapped into modules is by design, so one can execute sets of tests with a simple `include(file)`. Maybe I'm missing some features that `SafeTestsets` provides, but having an extra dependency to take care of for a bit of syntactic sugar doesn't seem worthwhile at the moment.

**Comment by devmotion** [comment]
In case it makes a difference for you: it's only a test dependency, so it won't be installed if a user adds Bootstrap. It's only added if you run the tests.

**Comment by juliangehring** [comment]
It doesn't make much of a difference that it is "only" a test dependency. We still need to take care of the dependency, and I just don't see that introducing `SafeTestsets` brings notable benefits that would make it worth it.

**Comment by juliangehring** [comment]
But maybe we can rename some of the test files - the current names are quite excessive ;) I'll have a look at that soon.

**Comment by devmotion** [comment]
> We still need to take care of the dependency, and I just don't see that introducing SafeTestsets brings notable benefits that would make it worth it.

I don't think a dependency on SafeTestsets would add any additional maintenance burden since the package is doing exactly what it was designed for and hence probably not much further development is required (and also not intended, I guess). The main advantage of using SafeTestsets is that the current structure of separating test sets into separate modules can be achieved without designing artificial modules by just using `@safetestset` instead of `@testset`. IMO that's more intuitive and, since it's just creating a module that runs a test set with the provided file wrapped in `@testset`, all `@testset`s in that file will be run and a summary of the failures in all `@testset`s will be returned (if there are any) with an appropriate, possibly user-provided test name, whereas currently execution would stop after the first failing `@testset`, i.e., all `@testset`s in each file are run sequentially and not grouped together.

But it feels like you've made your mind, so do you want me to close this PR?

**Comment by juliangehring** [comment]
As mentioned before, I don't see any real benefits of this change. Let's close this.

**Pull request closed without merging**
