### PR TITLE
allow DataFrames.jl 1.0 and bump package version

### PR DESCRIPTION
**Pull request by bkamins**

### CODE REVIEW

**Comment by haberdashPI** [comment]
One thought here: it seems like it should be relatively straightforward to remove `DataFrames` as a dependency and use `Tables` and `PrettyTables` in its stead, reducing the overall heft of Bootstrap's dependencies. I'd be happy to submit a PR for that.

**Comment by bkamins** [comment]
I would prefer it this way.

**Comment by juliangehring** [comment]
@bkamins Thank you! Could you change the PR to merge into `develop` instead of `master`?

**Review by juliangehring — CHANGES_REQUESTED** [review]
Some tests are failing with `DataFrames` v1.0, likely due to non-backwards compatible conversion methods between types.

**Comment by bkamins** [comment]
fixed

**Review by juliangehring — APPROVED** [review]
👍

**Pull request merged**
